### PR TITLE
Fix peer.end() (peer is a string)

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by RangerMauve** [comment]
@ralphtheninja Would you be down to change this PR to use a Map instead of a Set so we can track the connected peer's stream and then `end` it inside `destroy`?

**Comment by ralphtheninja** [comment]
@RangerMauve Sure. I'll try to squeeze that in this week.

**Comment by RangerMauve** [comment]
@ralphtheninja Thank you! No rush on this end of course 😁

**Comment by ralphtheninja** [comment]
@RangerMauve I have a few questions

In the `HyperSwarmProxyStream` `pump` is used to chain everything together:

https://github.com/RangerMauve/hyperswarm-proxy/blob/098abb114784edfe1322ca87ed9689a621190b1f/index.js#L17-L24

And `_closeAllStreams()` seems to end all connections:

https://github.com/RangerMauve/hyperswarm-proxy/blob/098abb114784edfe1322ca87ed9689a621190b1f/index.js#L79-L83

`this.connections` in `HyperSwarmProxyStream` is a `Set` of all `ProxyStream` instances so it seems to me that we don't need to do `stream.end()` in `HyperSwarmProxyClient`? This is under the assumption that `_closeAllStreams()` is invoked when `pump` ends and that that happens when the `HyperSwarmProxyStream` emits the `'close'` event.

I hope this makes sense. I might also miss something completely since I've just skimmed the code.

**Comment by ralphtheninja** [comment]
@RangerMauve Ping! I think this PR is fine, please check my investigations if you have a few minutes over. Cheers!

**Comment by RangerMauve** [comment]
@ralphtheninja Yes! Thanks again for double checking this,

**Review by RangerMauve — APPROVED** [review]

**Comment by RangerMauve** [comment]
Out in 1.5.1!

**Pull request merged**
